from . import discount_by_category
from . import discount_by_description_by_server
from . import discount_by_invoive_by_details
from . import discount_by_items
from . import inventory_history
from . import inventory_production
from . import inventory_summary_of_sales_by_customer_by_items
from . import inventory_wastage_items
from . import list_sales_items
from . import programming_summary_inventory
from . import purchase_with_all_details
from . import requisition_summary
from . import sales_by_menu_by_items
from . import sales_summary_of_sales_by_customer_by_items
from . import sales_wastage_items
from . import sales_items_ingredients